project:
  type: website
  output-dir: docs
  render:
    - "notes_24_25.qmd"
    - "tutorial.qmd"
website:
  title: 'Data Analysis Week 1'
  favicon: UofG_Coat_of_Arms.png
  navbar:
    logo: UofG.png
    left:
    - href: notes_24_25.qmd
      text: Notes
    - about.qmd
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css:
    - styles.css
    - include/webex.css
    toc: true
    include-after-body: include/webex.js
editor: visual
